<?php
/**
 * PSR-4 autoloader for the plugin's own namespace.
 *
 * @package ProductPublishGuard
 */

namespace ProductPublishGuard;

defined( 'ABSPATH' ) || exit;

/**
 * Maps `ProductPublishGuard\Some\Class_Name` to `src/Some/Class_Name.php`.
 *
 * Hand-written rather than generated by Composer so the release zip carries no
 * `vendor/` directory and cannot conflict with another plugin's autoloader.
 *
 * @since 1.0.0
 */
final class Autoloader {

	/**
	 * The namespace prefix this autoloader is responsible for.
	 *
	 * @since 1.0.0
	 * @var string
	 */
	private const PREFIX = 'ProductPublishGuard\\';

	/**
	 * Register the autoloader with SPL.
	 *
	 * @since 1.0.0
	 *
	 * @return void
	 */
	public static function register() {
		spl_autoload_register( array( __CLASS__, 'autoload' ) );
	}

	/**
	 * Resolve and load a class in the plugin namespace.
	 *
	 * Silently ignores every other namespace so that other autoloaders keep working.
	 *
	 * @since 1.0.0
	 *
	 * @param string $class_name Fully qualified class name.
	 * @return void
	 */
	public static function autoload( $class_name ) {
		if ( ! str_starts_with( $class_name, self::PREFIX ) ) {
			return;
		}

		$relative = substr( $class_name, strlen( self::PREFIX ) );
		$path     = WCPG_PATH . 'src/' . str_replace( '\\', '/', $relative ) . '.php';

		if ( file_exists( $path ) ) {
			require_once $path;
		}
	}
}
